import NavbarComponent from "@/components/NavbarComponent";
import "./globals.css";
import { Provider } from "@/context/provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        {/* <NavbarComponent /> */}
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
